[project]
name = "bookstack-api-code"
version = "0.1.0"
description = "Book Api Syncing Tool"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "python-dotenv>=1.1.1",
    "requests>=2.32.5",
]
